### ISSUE TITLE
Add `AcquisitionDuration` in JSON metadata for run1

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge-data#25]
A reviewer of the submitted paper is asking to compute CNR per unit time, which requires knowing the volume acquisition duration. This is a valid JSON field, and I suggest to add it for all subjects in this repository. Note that only 'run1' needs to be updated because the processing code will only look at 'run1' to fetch that information.

**Comment by alexfoias** [comment]
@jcohenadad I found some info here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3045184/

I checked SCT, but it doesn't seem like we have this feature yet.

Are we supposed to compute the CNR ? Should we do it like the paper (this was done in brain)? ![Screen Shot 2022-01-06 at 12 20 32 PM](https://user-images.githubusercontent.com/12564433/148423769-530c5740-a2bf-4644-acd5-7b421e5cfae9.png) 

What is the deadline ?

**Comment by jcohenadad** [comment]
> I checked SCT, but it doesn't seem like we have this feature yet.

right, we don't need that feature in SCT (too specific)-- the code is already [there](https://github.com/sct-pipeline/gm-challenge) 

> Are we supposed to compute the CNR ?

yes but this is unrelated to this issue-- this issue is just about adding `AcquisitionDuration`

> What is the deadline ?

ASAP (this should take you 10min to add this field for all subjects)-- thanks!
