### ISSUE TITLE
Use the JSON to also encode useful information

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge-data#3]
Following #2 it would be good to use the JSON to also encode useful information such as the field strength and the scanner vendor/model. Basically, some of the info that you find in the txt and/or pdf.

**Comment by alexfoias** [comment]
Okay, I will include that information.

**Comment by alexfoias** [comment]
@jcohenadad is there a document that link the subject id with the center ? I couldn't find the info [here](https://docs.google.com/document/d/1jDFZrpJ8nWunP9HjUTN5yDwT4cbnM5zaLDgDliLyMxc/edit#).

**Comment by jcohenadad** [comment]
> @jcohenadad is there a document that link the subject id with the center ? I couldn't find the info [here](https://docs.google.com/document/d/1jDFZrpJ8nWunP9HjUTN5yDwT4cbnM5zaLDgDliLyMxc/edit#).

check figure 2.
