### ISSUE TITLE
Sex not matching BIDS specification

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge-data#9]
According to the [specs](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/08-genetic-descriptor.html#subject-naming-and-participants-file), sex values should be M/F, not m/f as [currently the case](https://github.com/sct-pipeline/gm-challenge-data/blob/main/participants.tsv)

**Comment by alexfoias** [comment]
Fixed in https://github.com/sct-pipeline/gm-challenge-data/commit/61ce55166d8beff96a4641412b856107defdc399
